FROM mirrors.aliyun.com/centos:7.8.2003
#FROM openjdk:8-jdk
MAINTAINER djduan

ADD iflytek-cloud-caas-demo-consumer/target/*.jar  iflytek-cloud-caas-demo-consumer.jar

ENTRYPOINT ["java","-jar","iflytek-cloud-caas-demo-consumer.jar","--spring.cloud.nacos.config.server-addr=${NACOS_ADDR}", "--spring.cloud.nacos.discovery.server-addr=${NACOS_ADDR}"]
